const form = document.getElementById('certificateForm');
const badgeInput = document.getElementById('badgeInput');
const previewImage = document.getElementById('previewImage');
const previewPlaceholder = document.getElementById('previewPlaceholder');

let badgeDataUrl = '';

badgeInput.addEventListener('change', (event) => {
  const file = event.target.files?.[0];
  if (!file) {
    badgeDataUrl = '';
    previewImage.hidden = true;
    previewPlaceholder.hidden = false;
    return;
  }

  if (file.type !== 'image/png') {
    alert('Разрешены только PNG-файлы.');
    badgeInput.value = '';
    return;
  }

  const reader = new FileReader();
  reader.onload = () => {
    badgeDataUrl = String(reader.result || '');
    previewImage.src = badgeDataUrl;
    previewImage.hidden = false;
    previewPlaceholder.hidden = true;
  };
  reader.readAsDataURL(file);
});

form.addEventListener('submit', (event) => {
  event.preventDefault();

  const name = document.getElementById('studentName').value.trim();
  const certName = document.getElementById('certName').value.trim();
  const issueDate = document.getElementById('issueDate').value;

  if (!badgeDataUrl) {
    alert('Сначала загрузите PNG-бейдж.');
    return;
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });

  doc.setFillColor(246, 250, 255);
  doc.rect(0, 0, 842, 595, 'F');

  doc.setDrawColor(11, 95, 255);
  doc.setLineWidth(2);
  doc.roundedRect(26, 26, 790, 543, 12, 12, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(34);
  doc.text('Certificate of Achievement', 421, 130, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(71, 85, 105);
  doc.setFont('helvetica', 'normal');
  doc.text('This document certifies that', 421, 170, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(11, 95, 255);
  doc.text(name, 421, 220, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(`has completed: ${certName}`, 421, 260, { align: 'center' });

  const prettyDate = new Date(issueDate).toLocaleDateString('ru-RU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`Issued: ${prettyDate}`, 421, 290, { align: 'center' });

  doc.addImage(badgeDataUrl, 'PNG', 356, 325, 130, 130);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by Certification Showcase', 421, 520, { align: 'center' });

  const cleanName = name.toLowerCase().replace(/[^a-z0-9а-яё]+/gi, '-');
  doc.save(`certificate-${cleanName || 'user'}.pdf`);
});
